import os

PASS_TIMEOUT = 9000
FINE_REDUCTION_TIMEOUT = 120
CALLSITE_REDUCTION_INSTRUMENT_TIMEOUT = 45
VP_INSTRUMENTATION_TIMEOUT = 45
ORACLE_TIMEOUT = 30
WASM_OPT_PATH = os.environ.get("WASM_OPT_PATH", "wasm-opt")
WASM_TOOLS_PATH = os.environ.get("WASM_TOOLS_PATH", "wasm-tools")
WASM_REDUCE_DESTRUCTIVE_PATH = os.environ.get("WASM_REDUCE_DESTRUCTIVE_PATH", "wasm-reduce-destructive-m")
FRAMEWORK_IN_DEBUG = [False]
def is_debug_env():
    return FRAMEWORK_IN_DEBUG[0]