#!/usr/bin/env python3
"""Generates e2wr-ir's Inst enum and conversions from wasmparser 0.240's for_each_operator macro table.

Produces crates/e2wr-ir/src/inst_gen.rs:
- `enum Inst` (own instruction representation; payloads use wasmparser's owned types; br_table uses Vec)
- `Inst::from_operator(wasmparser::Operator)` decode conversion
- `Inst::write(&self, &mut wasm_encoder::Function)` encode (via wasm_encoder::reencode's
  RoundtripReencoder for payload type conversion, the same rules wasm-tools uses for round-trip conversion)

The encode-side field mapping rules match the translate! macro of wasm-encoder/src/reencode.rs:
field names decide identity/conversion, with special cases BrTable/TryTable/TypedSelectMulti/F32Const/F64Const/V128Const/
resume_table.

Usage: python3 tools/gen_inst_enum.py
"""

import re
import sys
from pathlib import Path

WASMPARSER_LIB = Path(
    "~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wasmparser-0.240.0/src/lib.rs"
).expanduser()
OUT = Path(__file__).resolve().parents[1] / "crates/e2wr-ir/src/inst_gen.rs"

# Storage type mapping (wasmparser macro-table types → Inst field types)
STORAGE = {
    "$crate::BlockType": "wasmparser::BlockType",
    "$crate::MemArg": "wasmparser::MemArg",
    "$crate::BrTable<'a>": "BrTableData",
    "$crate::Ieee32": "wasmparser::Ieee32",
    "$crate::Ieee64": "wasmparser::Ieee64",
    "$crate::V128": "wasmparser::V128",
    "$crate::HeapType": "wasmparser::HeapType",
    "$crate::RefType": "wasmparser::RefType",
    "$crate::ValType": "wasmparser::ValType",
    "Vec<$crate::ValType>": "Vec<wasmparser::ValType>",
    "$crate::TryTable": "wasmparser::TryTable",
    "$crate::Ordering": "wasmparser::Ordering",
    "$crate::ResumeTable": "wasmparser::ResumeTable",
    "u32": "u32",
    "i32": "i32",
    "u64": "u64",
    "i64": "i64",
    "u8": "u8",
    "[u8; 16]": "[u8; 16]",
}

CLONE_TYPES = ("Vec<$crate::ValType>", "$crate::TryTable", "$crate::ResumeTable")

# Encode side (Inst -> wasm_encoder::Instruction): conversion rules by field name
ENC_BY_FIELD = {
    "blockty": "rt.block_type(*{f}).unwrap()",
    "memarg": "rt.mem_arg(*{f}).unwrap()",
    "ty": "rt.val_type(*{f}).unwrap()",
    "hty": "rt.heap_type(*{f}).unwrap()",
    "from_ref_type": "rt.ref_type(*{f}).unwrap()",
    "to_ref_type": "rt.ref_type(*{f}).unwrap()",
    "ordering": "rt.ordering(*{f}).unwrap()",
}


def from_expr(field, ty):
    if ty == "$crate::BrTable<'a>":
        return None
    # op matched by value, fields bound by value (Copy types copied, owned types moved); no deref needed.
    return field


def enc_expr(field, ty):
    """Returns the encode-side expression (without the field-name prefix); owned types go through special cases, the rest by field name."""
    if field in ENC_BY_FIELD:
        return ENC_BY_FIELD[field].format(f=field)
    if ty == "$crate::BrTable<'a>":
        raise RuntimeError("BrTable must be handled as whole-op special case")
    if ty == "Vec<$crate::ValType>":
        return (
            "Cow::Owned("
            f"{field}.iter().map(|t| rt.val_type(*t).unwrap()).collect::<Vec<_>>())"
        )
    if ty == "$crate::TryTable":
        return (
            "Cow::Owned("
            f"{field}.catches.iter().map(|c| rt.catch(*c).unwrap()).collect::<Vec<_>>())"
        )
    if ty == "$crate::ResumeTable":
        return (
            "Cow::Owned("
            f"{field}.handlers.iter().map(|h| rt.handle(*h).unwrap()).collect::<Vec<_>>())"
        )
    if field == "value" and ty == "$crate::Ieee32":
        return f"(*{field}).into()"
    if field == "value" and ty == "$crate::Ieee64":
        return f"(*{field}).into()"
    if field == "value" and ty == "$crate::V128":
        return f"{field}.i128()"
    return f"*{field}"


def main() -> None:
    src = WASMPARSER_LIB.read_text()
    start = src.find("macro_rules! _for_each_operator_group")
    end = src.find("\n}\n", start)
    table = src[start:end]
    pat = re.compile(r"([A-Z][A-Za-z0-9]*)\s*(\{[^}]*\})?\s*=>\s*visit_\w+")
    entries = []
    for name, payload in pat.findall(table):
        fields = []
        if payload:
            for f in re.finditer(r"(\w+):\s*([^,}]+)", payload):
                fields.append((f.group(1), f.group(2).strip()))
        entries.append((name, fields))

    seen = set()
    for name, _ in entries:
        if name in seen:
            sys.exit(f"duplicate operator {name}")
        seen.add(name)

    lines = []
    w = lines.append
    w("// @generated by tools/gen_inst_enum.py — do not edit by hand.")
    w("// Source: the for_each_operator macro table of wasmparser 0.240.")
    w("#![allow(clippy::enum_variant_names)]")
    w("#![allow(clippy::redundant_field_names)]")
    w("")
    w("use super::inst::BrTableData;")
    w("")
    w("/// Own instruction representation: one variant per wasm opcode, with owned payloads.")
    w("/// Field names match wasmparser::Operator for easy cross-checking.")
    w("#[derive(Debug, Clone, PartialEq)]")
    w("pub enum Inst {")
    for name, fields in entries:
        if not fields:
            w(f"    {name},")
        elif len(fields) == 1 and fields[0][1] == "$crate::BrTable<'a>":
            w(f"    {name}(BrTableData),")
        else:
            w(f"    {name} {{")
            for f, t in fields:
                w(f"        {f}: {STORAGE[t]},")
            w("    },")
    w("}")
    w("")
    w("impl Inst {")
    w("    /// wasmparser decode result → Inst. br_table targets are collected into a Vec here.")
    w("    pub fn from_operator(op: wasmparser::Operator<'_>) -> Inst {")
    w("        use wasmparser::Operator;")
    w("        match op {")
    for name, fields in entries:
        if not fields:
            w(f"            Operator::{name} => Inst::{name},")
            continue
        pats = ", ".join(f for f, _ in fields)
        if len(fields) == 1 and fields[0][1] == "$crate::BrTable<'a>":
            w(f"            Operator::{name} {{ targets }} => Inst::{name}(BrTableData {{")
            w("                targets: targets")
            w("                    .targets()")
            w("                    .collect::<Result<Vec<_>, _>>()")
            w("                    .expect(\"valid br_table targets\"),")
            w("                default: targets.default(),")
            w("            }),")
            continue
        w(f"            Operator::{name} {{ {pats} }} => Inst::{name} {{")
        for f, t in fields:
            e = from_expr(f, t)
            if e is None:
                sys.exit(f"unhandled field {f}")
            w(f"                {f}: {e},")
        w("            },")
    w("            _ => unreachable!(\"wasmparser Operator variant set does not match the generated table\"),")
    w("        }")
    w("    }")
    w("")
    w("    /// Encode into a function body. Payload type conversions reuse wasm-encoder's reencode")
    w("    /// RoundtripReencoder (the same rules wasm-tools uses for round-trip conversion).")
    w("    pub fn write(&self, func: &mut wasm_encoder::Function) {")
    w("        let inst = self.to_instruction();")
    w("        func.instruction(&inst);")
    w("    }")
    w("")
    w("    /// Convert to a wasm-encoder instruction (for non-function-body uses such as constant expressions).")
    w("    pub fn to_instruction(&self) -> wasm_encoder::Instruction<'static> {")
    w("        let mut rt = wasm_encoder::reencode::RoundtripReencoder;")
    w("        self.to_encoder_instruction(&mut rt)")
    w("    }")
    w("")
    w("    fn to_encoder_instruction(")
    w("        &self,")
    w("        rt: &mut wasm_encoder::reencode::RoundtripReencoder,")
    w("    ) -> wasm_encoder::Instruction<'static> {")
    w("        use std::borrow::Cow;")
    w("        use wasm_encoder::Instruction;")
    w("        use wasm_encoder::reencode::Reencode as _;")
    w("        match self {")
    for name, fields in entries:
        if not fields:
            w(f"            Inst::{name} => Instruction::{name},")
            continue
        if name == "BrTable":
            w("            Inst::BrTable(d) => {")
            w("                Instruction::BrTable(Cow::Owned(d.targets.clone()), d.default)")
            w("            }")
            continue
        if len(fields) == 1 and fields[0][1] == "$crate::BrTable<'a>":
            sys.exit("unreachable")
        fpat = ", ".join(f for f, _ in fields)
        exprs = [enc_expr(f, t) for f, t in fields]
        # TryTable's blocktype comes from try_table.ty; special-cased
        if name == "TryTable":
            w("            Inst::TryTable { try_table } => Instruction::TryTable(")
            w("                rt.block_type(try_table.ty).unwrap(),")
            w(f"                {exprs[0]},")
            w("            ),")
            continue
        if len(fields) == 1:
            w(f"            Inst::{name} {{ {fpat} }} => Instruction::{name}({exprs[0]}),")
        else:
            w(f"            Inst::{name} {{ {fpat} }} => Instruction::{name} {{")
            for f, e in zip((f for f, _ in fields), exprs):
                w(f"                {f}: {e},")
            w("            },")
    w("        }")
    w("    }")
    w("}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} with {len(entries)} operators")


if __name__ == "__main__":
    main()
