// @generated by tools/gen_inst_types.py — do not edit by hand.
// Source: full_type_part of E2WR/init_parser_data/inst_data/*.json
// (concrete type candidates only; placeholder and manual instructions live in get_inst_ty_req in types.rs).
#![allow(clippy::all)]

use crate::inst_gen::Inst;
use crate::types::{FTy, TR, ValTy};

/// Candidate sets of concrete-typed instructions (context-free; None = handled by the manual path or the AST layer).
pub fn concrete_cands(inst: &Inst) -> Option<TR> {
    match inst {
        Inst::DataDrop { .. } => Some(TR::new([
            FTy::of(&[], &[]),
        ])),
        Inst::Drop { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[]),
            FTy::of(&[ValTy::I64], &[]),
            FTy::of(&[ValTy::F32], &[]),
            FTy::of(&[ValTy::F64], &[]),
            FTy::of(&[ValTy::V128], &[]),
            FTy::of(&[ValTy::Funcref], &[]),
            FTy::of(&[ValTy::Externref], &[]),
        ])),
        Inst::ElemDrop { .. } => Some(TR::new([
            FTy::of(&[], &[]),
        ])),
        Inst::F32Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Ceil { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Const { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::F32]),
        ])),
        Inst::F32ConvertI32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::F32]),
        ])),
        Inst::F32ConvertI32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::F32]),
        ])),
        Inst::F32ConvertI64S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::F32]),
        ])),
        Inst::F32ConvertI64U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::F32]),
        ])),
        Inst::F32Copysign { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32DemoteF64 { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F32]),
        ])),
        Inst::F32Div { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::F32Floor { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Ge { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::F32Gt { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::F32Le { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::F32Load { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::F32]),
        ])),
        Inst::F32Lt { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::F32Max { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Min { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::F32Nearest { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32ReinterpretI32 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::F32]),
        ])),
        Inst::F32Sqrt { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Store { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::F32], &[]),
        ])),
        Inst::F32Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32, ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32Trunc { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F32]),
        ])),
        Inst::F32x4Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Ceil { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4ConvertI32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4ConvertI32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4DemoteF64x2Zero { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Div { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4ExtractLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::F32]),
        ])),
        Inst::F32x4Floor { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Ge { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Gt { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Le { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Lt { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Max { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Min { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Nearest { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4PMax { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4PMin { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4ReplaceLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::F32], &[ValTy::V128]),
        ])),
        Inst::F32x4Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::V128]),
        ])),
        Inst::F32x4Sqrt { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F32x4Trunc { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Ceil { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Const { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::F64]),
        ])),
        Inst::F64ConvertI32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::F64]),
        ])),
        Inst::F64ConvertI32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::F64]),
        ])),
        Inst::F64ConvertI64S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::F64]),
        ])),
        Inst::F64ConvertI64U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::F64]),
        ])),
        Inst::F64Copysign { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Div { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::F64Floor { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Ge { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::F64Gt { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::F64Le { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::F64Load { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::F64]),
        ])),
        Inst::F64Lt { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::F64Max { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Min { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::F64Nearest { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64PromoteF32 { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::F64]),
        ])),
        Inst::F64ReinterpretI64 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::F64]),
        ])),
        Inst::F64Sqrt { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Store { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::F64], &[]),
        ])),
        Inst::F64Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64, ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64Trunc { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::F64]),
        ])),
        Inst::F64x2Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Ceil { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2ConvertLowI32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2ConvertLowI32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Div { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2ExtractLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::F64]),
        ])),
        Inst::F64x2Floor { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Ge { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Gt { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Le { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Lt { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Max { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Min { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Nearest { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2PMax { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2PMin { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2PromoteLowF32x4 { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2ReplaceLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::F64], &[ValTy::V128]),
        ])),
        Inst::F64x2Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::V128]),
        ])),
        Inst::F64x2Sqrt { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::F64x2Trunc { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8AddSatS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8AddSatU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8AllTrue { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I16x8AvgrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8Bitmask { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I16x8Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtAddPairwiseI8x16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtAddPairwiseI8x16U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtendHighI8x16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtendHighI8x16U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtendLowI8x16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtendLowI8x16U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtMulHighI8x16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtMulHighI8x16U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtMulLowI8x16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtMulLowI8x16U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ExtractLaneS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I16x8ExtractLaneU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I16x8GeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8GeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8GtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8GtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8LeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8LeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8LtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8LtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8MaxS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8MaxU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8MinS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8MinU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8NarrowI32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8NarrowI32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8Q15MulrSatS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8ReplaceLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I16x8Shl { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I16x8ShrS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I16x8ShrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I16x8Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I16x8Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8SubSatS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I16x8SubSatU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32And { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Clz { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Const { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::I32]),
        ])),
        Inst::I32Ctz { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32DivS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32DivU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Eqz { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Extend16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Extend8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32GeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32GeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32GtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32GtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32LeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32LeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Load { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Load16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Load16U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Load8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Load8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32LtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32LtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Or { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Popcnt { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32ReinterpretF32 { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::I32RemS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32RemU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Rotl { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Rotr { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Shl { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32ShrS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32ShrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32Store { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::I32Store16 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::I32Store8 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::I32Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32TruncF32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::I32TruncF32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::I32TruncF64S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::I32TruncF64U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::I32TruncSatF32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::I32TruncSatF32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I32]),
        ])),
        Inst::I32TruncSatF64S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::I32TruncSatF64U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I32]),
        ])),
        Inst::I32WrapI64 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I32Xor { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::I32x4Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4AllTrue { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I32x4Bitmask { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I32x4DotI16x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtAddPairwiseI16x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtAddPairwiseI16x8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtendHighI16x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtendHighI16x8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtendLowI16x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtendLowI16x8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtMulHighI16x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtMulHighI16x8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtMulLowI16x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtMulLowI16x8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ExtractLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I32x4GeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4GeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4GtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4GtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4LeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4LeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4LtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4LtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4MaxS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4MaxU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4MinS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4MinU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4ReplaceLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I32x4Shl { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I32x4ShrS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I32x4ShrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I32x4Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I32x4Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4TruncSatF32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4TruncSatF32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4TruncSatF64x2SZero { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I32x4TruncSatF64x2UZero { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64And { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Clz { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Const { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::I64]),
        ])),
        Inst::I64Ctz { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64DivS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64DivU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64Eqz { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64Extend16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Extend32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Extend8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64ExtendI32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64ExtendI32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64GeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64GeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64GtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64GtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64LeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64LeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64Load { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64Load16S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64Load16U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64Load32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64Load32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64Load8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64Load8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I64]),
        ])),
        Inst::I64LtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64LtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I32]),
        ])),
        Inst::I64Or { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Popcnt { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64ReinterpretF64 { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I64]),
        ])),
        Inst::I64RemS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64RemU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Rotl { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Rotr { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Shl { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64ShrS { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64ShrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64Store { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I64], &[]),
        ])),
        Inst::I64Store16 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I64], &[]),
        ])),
        Inst::I64Store32 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I64], &[]),
        ])),
        Inst::I64Store8 { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I64], &[]),
        ])),
        Inst::I64Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64TruncF32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I64]),
        ])),
        Inst::I64TruncF32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I64]),
        ])),
        Inst::I64TruncF64S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I64]),
        ])),
        Inst::I64TruncF64U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I64]),
        ])),
        Inst::I64TruncSatF32S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I64]),
        ])),
        Inst::I64TruncSatF32U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F32], &[ValTy::I64]),
        ])),
        Inst::I64TruncSatF64S { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I64]),
        ])),
        Inst::I64TruncSatF64U { .. } => Some(TR::new([
            FTy::of(&[ValTy::F64], &[ValTy::I64]),
        ])),
        Inst::I64Xor { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64, ValTy::I64], &[ValTy::I64]),
        ])),
        Inst::I64x2Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2AllTrue { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I64x2Bitmask { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I64x2Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtendHighI32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtendHighI32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtendLowI32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtendLowI32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtMulHighI32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtMulHighI32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtMulLowI32x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtMulLowI32x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ExtractLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I64]),
        ])),
        Inst::I64x2GeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2GtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2LeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2LtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2Mul { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I64x2ReplaceLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I64], &[ValTy::V128]),
        ])),
        Inst::I64x2Shl { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I64x2ShrS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I64x2ShrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I64x2Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I64], &[ValTy::V128]),
        ])),
        Inst::I64x2Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Abs { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Add { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16AddSatS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16AddSatU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16AllTrue { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I8x16AvgrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Bitmask { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I8x16Eq { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16ExtractLaneS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I8x16ExtractLaneU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::I8x16GeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16GeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16GtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16GtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16LeS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16LeU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16LtS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16LtU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16MaxS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16MaxU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16MinS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16MinU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16NarrowI16x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16NarrowI16x8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Ne { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Neg { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Popcnt { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16ReplaceLane { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I8x16Shl { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I8x16ShrS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I8x16ShrU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I8x16Shuffle { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::I8x16Sub { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16SubSatS { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16SubSatU { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::I8x16Swizzle { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::MemoryCopy { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::MemoryFill { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::MemoryGrow { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::I32]),
        ])),
        Inst::MemoryInit { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::MemorySize { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::I32]),
        ])),
        Inst::Nop { .. } => Some(TR::new([
            FTy::of(&[], &[]),
        ])),
        Inst::RefFunc { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::Funcref]),
        ])),
        Inst::RefIsNull { .. } => Some(TR::new([
            FTy::of(&[ValTy::Funcref], &[ValTy::I32]),
            FTy::of(&[ValTy::Externref], &[ValTy::I32]),
        ])),
        Inst::Select { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32, ValTy::I32], &[ValTy::I32]),
            FTy::of(&[ValTy::I64, ValTy::I64, ValTy::I32], &[ValTy::I64]),
            FTy::of(&[ValTy::F32, ValTy::F32, ValTy::I32], &[ValTy::F32]),
            FTy::of(&[ValTy::F64, ValTy::F64, ValTy::I32], &[ValTy::F64]),
            FTy::of(&[ValTy::V128, ValTy::V128, ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::TableCopy { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::TableInit { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::I32, ValTy::I32], &[]),
        ])),
        Inst::TableSize { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::I32]),
        ])),
        Inst::V128And { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128AndNot { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128AnyTrue { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::I32]),
        ])),
        Inst::V128Bitselect { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128Const { .. } => Some(TR::new([
            FTy::of(&[], &[ValTy::V128]),
        ])),
        Inst::V128Load { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load16Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128Load16Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load16x4S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load16x4U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load32Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128Load32Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load32Zero { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load32x2S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load32x2U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load64Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128Load64Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load64Zero { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load8Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128Load8Splat { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load8x8S { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Load8x8U { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32], &[ValTy::V128]),
        ])),
        Inst::V128Not { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128Or { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        Inst::V128Store { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[]),
        ])),
        Inst::V128Store16Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[]),
        ])),
        Inst::V128Store32Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[]),
        ])),
        Inst::V128Store64Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[]),
        ])),
        Inst::V128Store8Lane { .. } => Some(TR::new([
            FTy::of(&[ValTy::I32, ValTy::V128], &[]),
        ])),
        Inst::V128Xor { .. } => Some(TR::new([
            FTy::of(&[ValTy::V128, ValTy::V128], &[ValTy::V128]),
        ])),
        _ => None,
    }
}
