//! e2wr-ir: wasm module intermediate representation, encode/decode and snapshots (M2/M3) + type system (M5).
//!
//! Design principles and the frozen interface contract are recorded in the design notes. Layers:
//! - `module`: module-level intermediate representation (the object model of Python `WasmParser`);
//! - `inst`/`inst_gen`: instruction representation (`inst_gen` is generated by tools/gen_inst_enum.py);
//! - `decode`: wasm bytes → Module (wasmparser);
//! - `encode`: Module → wasm bytes (wasm-encoder, parser2wasm semantics);
//! - `snapshot`: the snapshot interface frozen for the reducer layer;
//! - `types`: stack-requirement types FTy/compose/match/candidate sets/stack states (M5,
//!   mirroring the new Python typeSys2.py baseline).

pub mod ast;
pub mod decode;
pub mod encode;
pub mod inst;
mod inst_gen;
mod inst_types_gen;
pub mod module;
pub mod mutation;
pub mod refs;
pub mod snapshot;
pub mod stack_infer;
pub mod types;

pub use inst::Inst;
pub use module::*;
// R-26: the crate root used to re-export mutation::{apply_mutation_and_encode, apply_mutations,
// DefEdit, Mutation, RawDef} and snapshot::SECTION_ENCODE_ORDER — downstream code
// uses full module paths (e2wr_ir::mutation::...); nobody used the root re-exports, removed.
pub use snapshot::{Snapshot, SectionKind};
